# fly.toml app configuration file generated for roadmr-cron-monitor on 2025-04-07T15:25:24Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'roadmr-cron-monitor'
primary_region = 'atl'

[build]

[env]
FLYRESTARTER_DATABASE="/data/restarter.db"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024

[[mounts]]
destination = "/data"
source = "sqlite_data"
initial_size = '1GB'
