"""monitor unique by slug+user

Revision ID: 04b9027329c0
Revises: d9749ed54a44
Create Date: 2025-05-16 12:39:58.009209

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "04b9027329c0"
down_revision: Union[str, None] = "d9749ed54a44"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("monitor") as bop:
        bop.drop_constraint(bop.f("unique_slug"), type_="unique")
        bop.create_unique_constraint(bop.f("uix_user_id_slug"), ["user_id", "slug"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("monitor") as bop:
        bop.drop_constraint(bop.f("uix_user_id_slug"), type_="unique")
        bop.create_unique_constraint(bop.f("unique_slug"), ["slug"])
    # ### end Alembic commands ###
