"""user email unique

Revision ID: 3796bbba5dae
Revises: 85ea47809d63
Create Date: 2025-04-24 17:26:59.039483

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3796bbba5dae"
down_revision: Union[str, None] = "85ea47809d63"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user") as bop:
        bop.create_unique_constraint(bop.f("unique_email"), ["email"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user") as bop:
        bop.drop_constraint(bop.f("unique_email"), type_="unique")
    # ### end Alembic commands ###
