"""add webhook last_called

Revision ID: c18851d8e12f
Revises: 5305e81d16fa
Create Date: 2025-04-22 16:39:14.656075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c18851d8e12f'
down_revision: Union[str, None] = '5305e81d16fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webhook', sa.Column('last_called', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('webhook', 'last_called')
    # ### end Alembic commands ###
