"""monitor slug unique

Revision ID: d9749ed54a44
Revises: 3796bbba5dae
Create Date: 2025-04-25 17:17:40.275344

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d9749ed54a44"
down_revision: Union[str, None] = "3796bbba5dae"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("monitor") as bop:
        bop.create_unique_constraint(bop.f("unique_slug"), ["slug"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("monitor") as bop:
        bop.drop_constraint(bop.f("unique_slug"), type_="unique")
    # ### end Alembic commands ###
